# Generated by Django 4.2.4 on 2023-08-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50)),
                ('name2', models.CharField(max_length=50)),
                ('name3', models.CharField(max_length=50)),
                ('name4', models.CharField(max_length=50)),
                ('name5', models.CharField(max_length=50)),
                ('name6', models.CharField(max_length=50)),
                ('name7', models.CharField(max_length=50)),
                ('name8', models.CharField(max_length=50)),
                ('name9', models.CharField(max_length=50)),
                ('name10', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('indication', models.TextField()),
                ('effect_on_dental_tissues', models.TextField()),
                ('effect_on_patient_treatment', models.TextField()),
                ('drug_interaction', models.TextField()),
            ],
        ),
    ]
