# Generated by Django 4.2.4 on 2023-08-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alter_drug_name1_alter_drug_name10_alter_drug_name2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='name1',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name10',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name2',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name3',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name4',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name5',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name6',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name7',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name8',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name9',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
