# Generated by Django 4.2.4 on 2023-08-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_alter_drug_name1_alter_drug_name10_alter_drug_name2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drug',
            options={'ordering': ['name1']},
        ),
        migrations.RemoveField(
            model_name='drug',
            name='name10',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='name3',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='name4',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='name5',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='name6',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='name7',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='name8',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='name9',
        ),
        migrations.AlterField(
            model_name='drug',
            name='name2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
