# Generated by Django 4.2.4 on 2023-08-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_alter_drug_options_remove_drug_name10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(blank=True, max_length=50, null=True)),
                ('name2', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField()),
                ('indication', models.TextField()),
                ('Presentations', models.TextField()),
                ('Dose', models.TextField()),
                ('Contraindications', models.TextField()),
                ('Precautions', models.TextField()),
                ('Unwanted_effects', models.TextField()),
                ('drug_interaction', models.TextField()),
            ],
            options={
                'ordering': ['name1'],
            },
        ),
        migrations.CreateModel(
            name='Drug3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(blank=True, max_length=50, null=True)),
                ('name2', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField()),
                ('indication', models.TextField()),
                ('Presentations', models.TextField()),
                ('Dose', models.TextField()),
                ('Contraindications', models.TextField()),
                ('Unwanted_effects', models.TextField()),
                ('drug_interaction', models.TextField()),
            ],
            options={
                'ordering': ['name1'],
            },
        ),
    ]
